### ISSUE TITLE
expokit.f has incompatible copyright

### ISSUE THREAD

**Issue by mbanck** [LBNL-AMO-MCTDHF/V1#32]
The file SRC/expokit.f is apparently taken from http://www.maths.uq.edu.au/expokit/fortran/expokit.f , however, the copyright for expokit (http://www.maths.uq.edu.au/expokit/copyright) reads:

```
Permission to use, copy, modify, and distribute EXPOKIT and its
supporting documentation for non-commercial purposes, is hereby
granted without fee, provided that this permission message and
copyright notice appear in all copies. Approval must be sought for
commercial purposes as testimony of its usage in applications.
```

First off, note that the LBNL-AMO-MCTDHF codebase leaves out the copyright notice (as far as I can tell, I didn't check all files), in violation of the copyright.

Second, the above is clearly not an open-source license (restriction against field of use, commercial usage in this case), and thus incompatible with the Apache license. This file should be replaced with a clean-room, open sourced implementation of the paper, hopefully there are Fortran-based open source implementation around, I have not checked that.

**Comment by danhax** [comment]
Hello...  I think you misunderstand; this is not commercial software.  You
write "restriction against field of use, commercial usage in this case" but
this is not commercial software.  It seems that I need to include that
message ("provided that this permission message and copyright notice appear
in all copies").

**Comment by mbanck** [comment]
It's the other way round: A user can only use expokit for non-commercial usage. That is a restriction on top of the Apache license which in turn makes LBNL-AMO-MCTDHF only usable for non-commercial usage, no longer making it open source. That does not mean that LBNL-AMO-MCTDHF is commercial software, but it is understood that the non-commercial limitation of the expokit copyright will apply to users of LBNL-AMO-MCTDHF as well.

A probable example would be somebody from SGI or Intel trying to optimize LBNL-AMO-MCTDHF for their systems or compilers - that'd be likely considered commercial use. Clear-cut end-user commercial use is less likely at this point I guess, but it might be a problem in the future.

In any case, this problem makes it impossible for Linux distributions like Fedora, Ubuntu, Debian or OpenSuSE to ship LBNL-AMO-MCTDHF as they only ship open source software. They could rip out expokit.f, but I guess that would mean the whole program would no longer work?

**Comment by djhaxton** [comment]
Expokit license has been included in commit https://github.com/LBNL-AMO-MCTDHF/V1/commit/f4bd7bbc24ece54e0a7418937a4b0dd8b6ddc035

in file

  https://github.com/LBNL-AMO-MCTDHF/V1/blob/master/EXPOKIT-LICENSE

and at top in file

  https://github.com/LBNL-AMO-MCTDHF/V1/blob/master/MCTDH.SRC/expokit.f

and the following inquiry has been sent:

Dear Dr Sidje,

I've been using your expokit package for many years and I think this is the first time I've sent you a message about it.

I've built a code to solve the quantum mechanical Schrodinger equation for molecules, and I make use of expokit in several parts of the program.

   https://github.com/LBNL-AMO-MCTDHF/V1
   https://commons.lbl.gov/display/csd/LBNL-AMO-MCTDHF

My desire is to release this code as open-source software.  However, the copyright on expokit

   http://www.maths.uq.edu.au/expokit/copyright

seems to prevent this.  Please see

   https://github.com/LBNL-AMO-MCTDHF/V1/issues/32

Can you suggest any solution?  Please let me know if you want me to take the code off-line due to my unauthorized use of expokit.  Currently it is available via the link above, open-source.  My understanding is, the license on expokit is inconsistent with open-source, e.g., companies cannot take my code and optimize it for their compilers if they want to.  I desire to fix this situation.  I'd like this code to be distributed under the Apache license or similar, as open-source software.  I can write replacements for expokit, but I'd prefer not to.

As you can see my copy of expokit.f

   https://github.com/LBNL-AMO-MCTDHF/V1/blob/master/MCTDH.SRC/expokit.f

is substantially modified for parallel computers and otherwise.  My modifications probably complicate the copyright issue.

Please let me know if you can grant me an open-source license, or if you have any suggestions.  Presently I have put your license in

   https://github.com/LBNL-AMO-MCTDHF/V1/blob/master/EXPOKIT-LICENSE

**Comment by djhaxton** [comment]
I believe we are ok...  See https://github.com/LBNL-AMO-MCTDHF/V1/commit/5797d3a99f60db7e0ba025c19f4272f6c3cc60f4

**Comment by djhaxton** [comment]
Still waiting on Roger for "Expokit may be used under the terms of the Apache license version 2.0"

**Comment by djhaxton** [comment]
Okey dokey

https://github.com/LBNL-AMO-MCTDHF/V1/commit/ffd7aa5cabdfdeee386e1867bb2714bf543b3e4f
